[logger]
level = "DEBUG"
[db]
dsn = "host=localhost user=homestead password=secret dbname=homestead sslmode=disable"
[storage]
type = "db"
[httpserver]
host = "localhost"
port = "1234"
[grpcserver]
host = "localhost"
port = "2345"
